<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Asta Musa">
<meta name="dcterms.date" content="2025-05-22">

<title>BRFSS 2023: Flu Shot Uptake and Insurance Status Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="brfss2023_flu_insurance_analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="brfss2023_flu_insurance_analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="brfss2023_flu_insurance_analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="brfss2023_flu_insurance_analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="brfss2023_flu_insurance_analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="brfss2023_flu_insurance_analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="brfss2023_flu_insurance_analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="brfss2023_flu_insurance_analysis_files/libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="brfss2023_flu_insurance_analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="brfss2023_flu_insurance_analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="brfss2023_flu_insurance_analysis_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BRFSS 2023: Flu Shot Uptake and Insurance Status Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Asta Musa </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 22, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Data Source</strong>: 2023 Behavioral Risk Factor Surveillance System (BRFSS), CDC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice

Attaching package: 'caret'

The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pscl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Classes and Methods for R originally developed in the
Political Science Computational Laboratory
Department of Political Science
Stanford University (2002-2015),
by and under the direction of Simon Jackman.
hurdle and zeroinfl functions by Achim Zeileis.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === 1. Data Acquisition &amp; Importation ===</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Objective: Import and load .XPT file using reproducible code</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Prompt user to select file interactively, improving portability</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>brfss_data <span class="ot">&lt;-</span> <span class="fu">read_xpt</span>(<span class="st">"LLCP2023.XPT"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># View variable names</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co">#names(brfss_data)</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># === 2. Data Cleaning &amp; Wrangling ===</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Objective: Select relevant variables, inspect and handle missing values, and recode for clarity</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Select a subset of the relevant variables for the analysis</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>brfss_subset <span class="ot">&lt;-</span> brfss_data <span class="sc">%&gt;%</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    PRIMINS1,       <span class="co"># Insurance status</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    CHECKUP1,       <span class="co"># Time since last routine checkup</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    FLUSHOT7,       <span class="co"># Flu shot in past 12 months</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    SEXVAR,         <span class="co"># Biological sex</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">_AGE80</span><span class="st">`</span>,       <span class="co"># Age (top-coded at 80+)</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>    EDUCA,          <span class="co"># Education level</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>    INCOME3,        <span class="co"># Income category</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">_RACEGR3</span><span class="st">`</span>      <span class="co"># Race/ethnicity group</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Explore missing and invalid codes</span></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(brfss_subset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    PRIMINS1        CHECKUP1        FLUSHOT7         SEXVAR         _AGE80     
 Min.   : 1.00   Min.   :1.000   Min.   :1.000   Min.   :1.00   Min.   :18.00  
 1st Qu.: 1.00   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:1.00   1st Qu.:41.00  
 Median : 3.00   Median :1.000   Median :2.000   Median :2.00   Median :58.00  
 Mean   :10.87   Mean   :1.435   Mean   :1.561   Mean   :1.53   Mean   :55.38  
 3rd Qu.: 5.00   3rd Qu.:1.000   3rd Qu.:2.000   3rd Qu.:2.00   3rd Qu.:71.00  
 Max.   :99.00   Max.   :9.000   Max.   :9.000   Max.   :2.00   Max.   :80.00  
 NA's   :5       NA's   :2       NA's   :27751                                 
     EDUCA          INCOME3         _RACEGR3    
 Min.   :1.000   Min.   : 1.00   Min.   :1.000  
 1st Qu.:4.000   1st Qu.: 6.00   1st Qu.:1.000  
 Median :5.000   Median : 8.00   Median :1.000  
 Mean   :5.063   Mean   :22.11   Mean   :1.833  
 3rd Qu.:6.000   3rd Qu.:10.00   3rd Qu.:2.000  
 Max.   :9.000   Max.   :99.00   Max.   :9.000  
 NA's   :9       NA's   :8075    NA's   :86     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(brfss_subset))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>PRIMINS1 CHECKUP1 FLUSHOT7   SEXVAR   _AGE80    EDUCA  INCOME3 _RACEGR3 
       5        2    27751        0        0        9     8075       86 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(brfss_subset, unique)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$PRIMINS1
 [1]  3  7  1  2 88 99 10  9  4  5 77  8  6 NA

$CHECKUP1
[1]  2  1  3  8  4  7  9 NA

$FLUSHOT7
[1]  2  1 NA  7  9

$SEXVAR
[1] 2 1

$`_AGE80`
 [1] 80 78 76 62 75 59 68 79 72 73 69 70 67 56 77 49 38 64 39 71 60 65 37 55 61
[26] 74 44 48 53 66 29 63 57 43 54 19 58 46 45 24 40 50 52 47 51 30 31 33 42 23
[51] 28 25 32 36 22 41 27 20 26 35 21 34 18

$EDUCA
[1]  5  4  6  3  2  9  1 NA

$INCOME3
 [1] 99  2  7  6  9  3 77  5  4  1 NA  8 11 10

$`_RACEGR3`
[1]  1  2  9  3  4  5 NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Filter out invalid survey codes (e.g., 7, 9, 77, 99)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>brfss_filtered <span class="ot">&lt;-</span> brfss_subset <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span>PRIMINS1 <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">9</span>),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span>CHECKUP1 <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">9</span>),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span>FLUSHOT7 <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">9</span>),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span>SEXVAR <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">9</span>),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span>EDUCA <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">9</span>),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span>INCOME3 <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">77</span>, <span class="dv">99</span>),</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">_AGE80</span><span class="st">`</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Recode variables into readable factors and labels</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>brfss_clean <span class="ot">&lt;-</span> brfss_filtered <span class="sc">%&gt;%</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">insured =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(PRIMINS1 <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">checkup_recent =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(CHECKUP1 <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Within past year"</span>, <span class="st">"Longer ago"</span>)),</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">flu_shot =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(FLUSHOT7 <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)),</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">sex =</span> <span class="fu">factor</span>(SEXVAR, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Female"</span>)),</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">age =</span> <span class="st">`</span><span class="at">_AGE80</span><span class="st">`</span>,</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">education =</span> <span class="fu">factor</span>(EDUCA, <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Never attended"</span>, <span class="st">"Grades 1-8"</span>, <span class="st">"Grades 9-11"</span>, <span class="st">"High school"</span>, <span class="st">"Some college"</span>, <span class="st">"College graduate"</span>)),</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">income =</span> <span class="fu">factor</span>(INCOME3),</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">race_group =</span> <span class="fu">factor</span>(<span class="st">`</span><span class="at">_RACEGR3</span><span class="st">`</span>)</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(brfss_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "PRIMINS1"       "CHECKUP1"       "FLUSHOT7"       "SEXVAR"        
 [5] "_AGE80"         "EDUCA"          "INCOME3"        "_RACEGR3"      
 [9] "insured"        "checkup_recent" "flu_shot"       "sex"           
[13] "age"            "education"      "income"         "race_group"    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(brfss_clean))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      PRIMINS1       CHECKUP1       FLUSHOT7         SEXVAR         _AGE80 
             3              2          19512              0              0 
         EDUCA        INCOME3       _RACEGR3        insured checkup_recent 
             6           7291             57              3              2 
      flu_shot            sex            age      education         income 
         19512              0              0              6           7291 
    race_group 
            57 </code></pre>
</div>
</div>
<section id="data-cleaning-notes" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-notes">Data Cleaning Notes</h3>
<p>Following initial import, a review of the selected BRFSS variables revealed a significant presence of invalid or missing values. For instance:</p>
<ul>
<li><strong>FLUSHOT7</strong> had over <strong>27,000 missing or invalid entries</strong>, necessitating removal or recoding for accurate modeling.</li>
<li><strong>INCOME3</strong> showed over <strong>7,000 missing or non-informative entries</strong> (e.g., “Don’t know”, “Refused”), while <strong>EDUCA</strong> had 6 entries coded as ‘9’, which indicates “Refused” or “Don’t know”.</li>
<li>**_AGE80** had no missing values, suggesting reliable age reporting up to the top-coded 80+ category.</li>
<li>Categorical fields like <strong>PRIMINS1</strong> (insurance status) and <strong>CHECKUP1</strong> (time since last checkup) included BRFSS placeholder codes (7, 9) for “Don’t know/refused”, which were filtered out for clarity and accuracy.</li>
</ul>
<p>By excluding these ambiguous entries and recoding key fields into interpretable labels (e.g., “Yes”/“No”, “Male”/“Female”), the dataset is refined into a clean analytic sample. This ensures that downstream analysis is both valid and easily communicable to non-technical stakeholders.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === 3. Exploratory Data Analysis (EDA) ===</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Objective: Explore key variables and relationships to inform analysis</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Step 1: Categorical Distributions ----</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>insured_tab <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(insured)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>flu_shot_tab <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(flu_shot)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>checkup_tab <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(checkup_recent)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>sex_tab <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(sex)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>race_tab <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(race_group)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>edu_tab <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(education)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>income_tab <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(income)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Step 2: Cross-Tabulations ----</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>flu_by_ins <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(flu_shot, insured) <span class="sc">%&gt;%</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_percentages</span>(<span class="st">"row"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="st">"row"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_title</span>()</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>checkup_by_ins <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(checkup_recent, insured) <span class="sc">%&gt;%</span></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_percentages</span>(<span class="st">"row"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="st">"row"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_title</span>()</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Step 3: Visual Explorations ----</span></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>plot_flu_income <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span></span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">fill =</span> flu_shot)) <span class="sc">+</span></span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Flu Shot Uptake by Income Level"</span>,</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion"</span>,</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Income Category"</span>,</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Flu Shot"</span></span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a>plot_checkup_edu <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span></span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> education, <span class="at">fill =</span> checkup_recent)) <span class="sc">+</span></span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Routine Checkup by Education Level"</span>,</span>
<span id="cb21-47"><a href="#cb21-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion"</span>,</span>
<span id="cb21-48"><a href="#cb21-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Education Level"</span>,</span>
<span id="cb21-49"><a href="#cb21-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Checkup Timing"</span></span>
<span id="cb21-50"><a href="#cb21-50" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-51"><a href="#cb21-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb21-52"><a href="#cb21-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb21-53"><a href="#cb21-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-54"><a href="#cb21-54" aria-hidden="true" tabindex="-1"></a>plot_age_flu <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span></span>
<span id="cb21-55"><a href="#cb21-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">fill =</span> flu_shot)) <span class="sc">+</span></span>
<span id="cb21-56"><a href="#cb21-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb21-57"><a href="#cb21-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-58"><a href="#cb21-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Age Distribution by Flu Shot Status"</span>,</span>
<span id="cb21-59"><a href="#cb21-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb21-60"><a href="#cb21-60" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb21-61"><a href="#cb21-61" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-62"><a href="#cb21-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb21-63"><a href="#cb21-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-64"><a href="#cb21-64" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Step 4: Display Outputs ----</span></span>
<span id="cb21-65"><a href="#cb21-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-66"><a href="#cb21-66" aria-hidden="true" tabindex="-1"></a>insured_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> insured      n      percent valid_percent
      No 193328 5.927652e-01     0.5927707
     Yes 132815 4.072256e-01     0.4072293
    &lt;NA&gt;      3 9.198334e-06            NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>flu_shot_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> flu_shot      n    percent valid_percent
       No 154946 0.47508171     0.5053125
      Yes 151688 0.46509232     0.4946875
     &lt;NA&gt;  19512 0.05982597            NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>checkup_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   checkup_recent      n      percent valid_percent
       Longer ago  62218 1.907673e-01     0.1907685
 Within past year 263926 8.092265e-01     0.8092315
             &lt;NA&gt;      2 6.132223e-06            NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>sex_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    sex      n   percent
   Male 154477 0.4736437
 Female 171669 0.5263563</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>race_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> race_group      n      percent valid_percent
          1 239439 0.7341466705    0.73427500
          2  24614 0.0754692684    0.07548246
          3  18073 0.0554138331    0.05542352
          4   7489 0.0229621090    0.02296612
          5  31687 0.0971558750    0.09717286
          9   4787 0.0146774757    0.01468004
       &lt;NA&gt;     57 0.0001747684            NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>edu_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        education      n      percent valid_percent
   Never attended    389 1.192717e-03   0.001192739
       Grades 1-8   5466 1.675937e-02   0.016759674
      Grades 9-11  11158 3.421167e-02   0.034212301
      High school  76869 2.356889e-01   0.235693261
     Some college  85735 2.628731e-01   0.262877905
 College graduate 146523 4.492559e-01   0.449264120
             &lt;NA&gt;      6 1.839667e-05            NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>income_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> income     n    percent valid_percent
      1  8167 0.02504093    0.02561352
      2  8907 0.02730986    0.02793433
      3 11568 0.03546878    0.03627981
      4 16222 0.04973846    0.05087579
      5 34662 0.10627756    0.10870772
      6 43014 0.13188572    0.13490144
      7 53077 0.16274000    0.16646124
      8 45600 0.13981468    0.14301171
      9 49058 0.15041730    0.15385677
     10 22985 0.07047457    0.07208606
     11 25595 0.07847712    0.08027160
   &lt;NA&gt;  7291 0.02235502            NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>flu_by_ins</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    insured                                       
 flu_shot                No               Yes                  NA_
       No 0.572715655776851 0.427284344223149                    0
      Yes 0.611854596276568 0.388138811244133   6.592479299615e-06
     &lt;NA&gt; 0.603577285772858 0.396320213202132  0.00010250102501025
    Total  1.78814753782628  1.21174336866941 0.000109093504309865</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>checkup_by_ins</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            insured                                       
   checkup_recent                No               Yes                  NA_
       Longer ago  0.53388087048764  0.46611912951236                    0
 Within past year 0.606651106749619 0.393345104309541 3.78894083947773e-06
             &lt;NA&gt;                 0                 0                    1
            Total  1.14053197723726 0.859464233821901     1.00000378894084</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>plot_flu_income</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="brfss2023_flu_insurance_analysis_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>plot_checkup_edu</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="brfss2023_flu_insurance_analysis_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>plot_age_flu</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="brfss2023_flu_insurance_analysis_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Insurance Status:</strong><br>
Approximately 59.3% of respondents reported not having insurance coverage, while only 40.7% reported being insured. This suggests a substantial portion of the population surveyed lacks access to financial protection for health services.</p>
<p><strong>Flu Shot Uptake:</strong><br>
Among valid responses, flu shot coverage is nearly evenly split: 50.5% did not receive the flu shot in the past year, while 49.5% did. However, a significant portion (~6%) had missing responses, indicating possible survey fatigue or uncertainty.</p>
<p><strong>Routine Checkups:</strong><br>
Over 80% of respondents had a routine medical checkup within the past year, signaling strong preventive care engagement. Still, nearly 20% had not seen a provider in over a year — a gap worth exploring in relation to socioeconomic or demographic factors.</p>
<p><strong>Sex Distribution:</strong><br>
The sample has a fairly balanced sex distribution, with slightly more females (52.6%) than males (47.4%).</p>
<p><strong>Race/Ethnicity Groupings:</strong><br>
Most respondents identified with race group 1 (73.4%), followed by group 5 (9.7%), group 2 (7.5%), and others. Group definitions follow BRFSS coding; documentation is needed for interpretation. A small amount of data is missing (~0.02%).</p>
<p><strong>Education Levels:</strong><br>
A majority of participants had some college (26.3%) or were college graduates (44.9%). Only a small fraction (1.2%) reported no formal education. This skew toward higher education may influence health-seeking behaviors and insurance coverage.</p>
<p><strong>Income Distribution:</strong><br>
The income distribution is spread across all brackets, with the largest groups earning between levels 6–9 (representing low to mid-income ranges). High-income respondents (levels 10–11) comprise about 15% of the dataset, while about 2.2% had missing income data.</p>
<p><strong>Flu Shot by Insurance Status:</strong><br>
Among insured individuals, 38.8% received the flu shot, compared to 42.7% of the uninsured. Interestingly, the uninsured reported slightly higher flu shot rates than expected — suggesting that flu vaccination may be accessible via free or public sources.</p>
<p><strong>Routine Checkups by Insurance Status:</strong><br>
Among those with recent checkups, 60.7% were uninsured and only 39.3% were insured. This appears counterintuitive and may warrant further review — including data coding, survey skip patterns, or alternative explanations such as use of public health clinics.</p>
<p><strong>Visualization Summary:</strong><br>
The exploratory plots reveal key patterns in preventive care uptake. Flu shot uptake tends to increase with income level, suggesting financial barriers may influence vaccination behavior. Similarly, routine checkup rates improve with higher education levels, indicating a potential link between health literacy and healthcare engagement. Age distribution shows older adults are more likely to have received a flu shot, which aligns with public health campaigns targeting seniors. These patterns highlight how socioeconomic and demographic factors intersect with preventive care behaviors, reinforcing the importance of equity-oriented strategies in healthcare delivery.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === 4. Modeling &amp; Analysis ===</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Objective: Use logistic regression to analyze predictors of flu shot uptake</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Step 1: Prepare Data ----</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows with missing values in model variables</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>brfss_model <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(flu_shot, insured, age, sex, income, education, race_group)</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Step 2: Fit Logistic Regression Model ----</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit logistic regression model</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>flu_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  flu_shot <span class="sc">~</span> insured <span class="sc">+</span> age <span class="sc">+</span> sex <span class="sc">+</span> income <span class="sc">+</span> education <span class="sc">+</span> race_group,</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> brfss_model,</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Step 3: Summarize Model ----</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy model summary with odds ratios and 95% confidence intervals</span></span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>flu_model_summary <span class="ot">&lt;-</span> <span class="fu">tidy</span>(flu_model, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a><span class="co"># View model output</span></span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a>flu_model_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 7
   term        estimate std.error statistic   p.value conf.low conf.high
   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)   0.0865  0.120       -20.4  1.20e- 92   0.0682     0.109
 2 insuredYes    1.02    0.00961       2.50 1.23e-  2   1.01       1.04 
 3 age           1.03    0.000261    129.   0           1.03       1.03 
 4 sexFemale     1.30    0.00777      33.3  1.54e-243   1.28       1.32 
 5 income2       1.10    0.0338        2.81 4.98e-  3   1.03       1.18 
 6 income3       1.07    0.0322        1.96 5.01e-  2   1.00       1.13 
 7 income4       1.07    0.0304        2.17 3.02e-  2   1.01       1.13 
 8 income5       1.09    0.0278        3.24 1.20e-  3   1.04       1.16 
 9 income6       1.15    0.0275        4.97 6.68e-  7   1.09       1.21 
10 income7       1.24    0.0274        7.71 1.28e- 14   1.17       1.30 
# ℹ 14 more rows</code></pre>
</div>
</div>
<p><strong>Model Interpretation:</strong><br>
The logistic regression model estimates the odds of receiving a flu shot based on demographic and socioeconomic predictors. Being insured is associated with higher odds of flu shot uptake, reinforcing the importance of health coverage in preventive care. Older individuals are more likely to get vaccinated, aligning with risk-based public health targeting. Education and income both show positive associations with flu vaccination likelihood, suggesting social determinants play a substantial role. Race and sex also emerge as influential, highlighting disparities that may warrant further investigation or targeted intervention. These findings offer actionable insights for policymakers and healthcare providers aiming to improve vaccination rates equitably.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === 5. Statistical Modeling &amp; Interpretation ===</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Objective: Use logistic regression to model flu shot uptake based on insurance and demographics</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Prepare Data</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to keep only complete cases for modeling variables</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>brfss_model <span class="ot">&lt;-</span> brfss_clean <span class="sc">%&gt;%</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(flu_shot, insured, age, sex, income, education, race_group)</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode 'flu_shot' as a binary outcome: Yes = 1, No = 0</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>brfss_model <span class="ot">&lt;-</span> brfss_model <span class="sc">%&gt;%</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">flu_shot_binary =</span> <span class="fu">if_else</span>(flu_shot <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Fit Logistic Regression Model</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Model flu shot uptake based on insurance, age, sex, income, education, and race</span></span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>flu_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>  flu_shot_binary <span class="sc">~</span> insured <span class="sc">+</span> age <span class="sc">+</span> sex <span class="sc">+</span> income <span class="sc">+</span> education <span class="sc">+</span> race_group,</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> brfss_model,</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Summarize Model Output</span></span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flu_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = flu_shot_binary ~ insured + age + sex + income + 
    education + race_group, family = "binomial", data = brfss_model)

Coefficients:
                            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)               -2.4477622  0.1198931 -20.416  &lt; 2e-16 ***
insuredYes                 0.0240407  0.0096080   2.502  0.01234 *  
age                        0.0336450  0.0002607 129.062  &lt; 2e-16 ***
sexFemale                  0.2588093  0.0077656  33.328  &lt; 2e-16 ***
income2                    0.0949788  0.0338189   2.808  0.00498 ** 
income3                    0.0630040  0.0321643   1.959  0.05013 .  
income4                    0.0658552  0.0303813   2.168  0.03019 *  
income5                    0.0901327  0.0278383   3.238  0.00120 ** 
income6                    0.1368614  0.0275343   4.971 6.68e-07 ***
income7                    0.2114611  0.0274354   7.708 1.28e-14 ***
income8                    0.2829655  0.0279456  10.126  &lt; 2e-16 ***
income9                    0.3659293  0.0281136  13.016  &lt; 2e-16 ***
income10                   0.4255468  0.0301279  14.125  &lt; 2e-16 ***
income11                   0.5823864  0.0299784  19.427  &lt; 2e-16 ***
educationGrades 1-8       -0.1481946  0.1201883  -1.233  0.21757    
educationGrades 9-11      -0.2439505  0.1184195  -2.060  0.03939 *  
educationHigh school      -0.1584829  0.1168825  -1.356  0.17513    
educationSome college      0.0397587  0.1169064   0.340  0.73379    
educationCollege graduate  0.5317718  0.1169112   4.549 5.40e-06 ***
race_group2               -0.2614283  0.0150742 -17.343  &lt; 2e-16 ***
race_group3               -0.0146112  0.0171553  -0.852  0.39438    
race_group4               -0.2029986  0.0260025  -7.807 5.86e-15 ***
race_group5               -0.1082534  0.0145555  -7.437 1.03e-13 ***
race_group9               -0.4887056  0.0333647 -14.647  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 424978  on 306581  degrees of freedom
Residual deviance: 390006  on 306558  degrees of freedom
AIC: 390054

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Generate Odds Ratios</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(flu_model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              (Intercept)                insuredYes                       age 
               0.08648691                1.02433203                1.03421739 
                sexFemale                   income2                   income3 
               1.29538681                1.09963550                1.06503108 
                  income4                   income5                   income6 
               1.06807208                1.09431950                1.14666919 
                  income7                   income8                   income9 
               1.23548194                1.32705932                1.44185326 
                 income10                  income11       educationGrades 1-8 
               1.53042699                1.79030567                0.86226329 
     educationGrades 9-11      educationHigh school     educationSome college 
               0.78352644                0.85343752                1.04055965 
educationCollege graduate               race_group2               race_group3 
               1.70194513                0.76995107                0.98549503 
              race_group4               race_group5               race_group9 
               0.81627935                0.89740016                0.61341990 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Tidy summary for presentation</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(flu_model, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(p.value) <span class="sc">%&gt;%</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>, <span class="at">caption =</span> <span class="st">"Logistic Regression Results (Odds Ratios)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Logistic Regression Results (Odds Ratios)</caption>
<colgroup>
<col style="width: 31%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">1.034</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">129.062</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.034</td>
<td style="text-align: right;">1.035</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexFemale</td>
<td style="text-align: right;">1.295</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">33.328</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.276</td>
<td style="text-align: right;">1.315</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.086</td>
<td style="text-align: right;">0.120</td>
<td style="text-align: right;">-20.416</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.068</td>
<td style="text-align: right;">0.109</td>
</tr>
<tr class="even">
<td style="text-align: left;">income11</td>
<td style="text-align: right;">1.790</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">19.427</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.688</td>
<td style="text-align: right;">1.899</td>
</tr>
<tr class="odd">
<td style="text-align: left;">race_group2</td>
<td style="text-align: right;">0.770</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">-17.343</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.748</td>
<td style="text-align: right;">0.793</td>
</tr>
<tr class="even">
<td style="text-align: left;">race_group9</td>
<td style="text-align: right;">0.613</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">-14.647</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.575</td>
<td style="text-align: right;">0.655</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income10</td>
<td style="text-align: right;">1.530</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">14.125</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.443</td>
<td style="text-align: right;">1.624</td>
</tr>
<tr class="even">
<td style="text-align: left;">income9</td>
<td style="text-align: right;">1.442</td>
<td style="text-align: right;">0.028</td>
<td style="text-align: right;">13.016</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.365</td>
<td style="text-align: right;">1.524</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income8</td>
<td style="text-align: right;">1.327</td>
<td style="text-align: right;">0.028</td>
<td style="text-align: right;">10.126</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.256</td>
<td style="text-align: right;">1.402</td>
</tr>
<tr class="even">
<td style="text-align: left;">race_group4</td>
<td style="text-align: right;">0.816</td>
<td style="text-align: right;">0.026</td>
<td style="text-align: right;">-7.807</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.776</td>
<td style="text-align: right;">0.859</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income7</td>
<td style="text-align: right;">1.235</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">7.708</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.171</td>
<td style="text-align: right;">1.304</td>
</tr>
<tr class="even">
<td style="text-align: left;">race_group5</td>
<td style="text-align: right;">0.897</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">-7.437</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.872</td>
<td style="text-align: right;">0.923</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income6</td>
<td style="text-align: right;">1.147</td>
<td style="text-align: right;">0.028</td>
<td style="text-align: right;">4.971</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.087</td>
<td style="text-align: right;">1.210</td>
</tr>
<tr class="even">
<td style="text-align: left;">educationCollege graduate</td>
<td style="text-align: right;">1.702</td>
<td style="text-align: right;">0.117</td>
<td style="text-align: right;">4.549</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.356</td>
<td style="text-align: right;">2.145</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income5</td>
<td style="text-align: right;">1.094</td>
<td style="text-align: right;">0.028</td>
<td style="text-align: right;">3.238</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">1.036</td>
<td style="text-align: right;">1.156</td>
</tr>
<tr class="even">
<td style="text-align: left;">income2</td>
<td style="text-align: right;">1.100</td>
<td style="text-align: right;">0.034</td>
<td style="text-align: right;">2.808</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">1.029</td>
<td style="text-align: right;">1.175</td>
</tr>
<tr class="odd">
<td style="text-align: left;">insuredYes</td>
<td style="text-align: right;">1.024</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">2.502</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">1.005</td>
<td style="text-align: right;">1.044</td>
</tr>
<tr class="even">
<td style="text-align: left;">income4</td>
<td style="text-align: right;">1.068</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">2.168</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">1.006</td>
<td style="text-align: right;">1.134</td>
</tr>
<tr class="odd">
<td style="text-align: left;">educationGrades 9-11</td>
<td style="text-align: right;">0.784</td>
<td style="text-align: right;">0.118</td>
<td style="text-align: right;">-2.060</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: right;">0.622</td>
<td style="text-align: right;">0.990</td>
</tr>
<tr class="even">
<td style="text-align: left;">income3</td>
<td style="text-align: right;">1.065</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">1.959</td>
<td style="text-align: right;">0.050</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.134</td>
</tr>
<tr class="odd">
<td style="text-align: left;">educationHigh school</td>
<td style="text-align: right;">0.853</td>
<td style="text-align: right;">0.117</td>
<td style="text-align: right;">-1.356</td>
<td style="text-align: right;">0.175</td>
<td style="text-align: right;">0.680</td>
<td style="text-align: right;">1.075</td>
</tr>
<tr class="even">
<td style="text-align: left;">educationGrades 1-8</td>
<td style="text-align: right;">0.862</td>
<td style="text-align: right;">0.120</td>
<td style="text-align: right;">-1.233</td>
<td style="text-align: right;">0.218</td>
<td style="text-align: right;">0.682</td>
<td style="text-align: right;">1.093</td>
</tr>
<tr class="odd">
<td style="text-align: left;">race_group3</td>
<td style="text-align: right;">0.985</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">-0.852</td>
<td style="text-align: right;">0.394</td>
<td style="text-align: right;">0.953</td>
<td style="text-align: right;">1.019</td>
</tr>
<tr class="even">
<td style="text-align: left;">educationSome college</td>
<td style="text-align: right;">1.041</td>
<td style="text-align: right;">0.117</td>
<td style="text-align: right;">0.340</td>
<td style="text-align: right;">0.734</td>
<td style="text-align: right;">0.829</td>
<td style="text-align: right;">1.311</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 6: Model Evaluation</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Pseudo R-squared to evaluate model fit</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pR2</span>(flu_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fitting null model for pseudo-r2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          llh       llhNull            G2      McFadden          r2ML 
-1.950031e+05 -2.124891e+05  3.497203e+04  8.229135e-02  1.078052e-01 
         r2CU 
 1.437456e-01 </code></pre>
</div>
</div>
</section>
<section id="statistical-modeling-and-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="statistical-modeling-and-interpretation">Statistical Modeling and Interpretation</h3>
<p>To better understand the predictors of flu shot uptake, we fit a logistic regression model using key demographic and access variables. The binary outcome was whether the respondent had received a flu shot in the past 12 months (<code>Yes = 1</code>, <code>No = 0</code>).</p>
<section id="key-findings" class="level4">
<h4 class="anchored" data-anchor-id="key-findings">Key Findings:</h4>
<ul>
<li><strong>Insurance Coverage</strong>: Individuals with insurance were <strong>2.4% more likely</strong> to report flu shot uptake than uninsured individuals (<code>OR = 1.02</code>, <em>p</em> = 0.012), indicating a modest but statistically significant association.</li>
<li><strong>Age</strong>: Older age was strongly associated with increased flu shot uptake (<code>OR = 1.03</code>, <em>p</em> &lt; 0.001), suggesting increased preventive health behavior with age.</li>
<li><strong>Gender</strong>: Females had <strong>30% higher odds</strong> of receiving a flu shot than males (<code>OR = 1.30</code>, <em>p</em> &lt; 0.001), consistent with literature on gendered health-seeking behavior.</li>
<li><strong>Income Gradient</strong>: There was a clear trend of increasing flu shot uptake with higher income levels. For example:
<ul>
<li>Income Level 8: <code>OR = 1.33</code><br>
</li>
<li>Income Level 11: <code>OR = 1.79</code><br>
This suggests higher-income individuals were significantly more likely to receive flu shots, possibly reflecting better access or health awareness.</li>
</ul></li>
<li><strong>Education</strong>: College graduates had the highest odds of flu shot uptake (<code>OR = 1.70</code>, <em>p</em> &lt; 0.001). Those with some college education showed no significant difference, while individuals with <strong>Grades 9–11</strong> education had <strong>22% lower odds</strong> (<code>OR = 0.78</code>, <em>p</em> = 0.039).</li>
<li><strong>Race/Ethnicity</strong>: Compared to the reference group, several race categories had <strong>lower odds</strong> of flu shot uptake. For example:
<ul>
<li><code>race_group2</code>: <code>OR = 0.77</code><br>
</li>
<li><code>race_group9</code>: <code>OR = 0.61</code> — the lowest among groups, indicating potential structural or access barriers.</li>
</ul></li>
</ul>
</section>
<section id="model-fit" class="level4">
<h4 class="anchored" data-anchor-id="model-fit">Model Fit:</h4>
<ul>
<li><strong>McFadden’s Pseudo R² = 0.082</strong>, which indicates moderate explanatory power for a cross-sectional survey.</li>
<li><strong>AIC = 390054</strong> and <strong>Residual Deviance</strong> significantly lower than the null deviance, suggesting the model improves upon chance predictions.</li>
</ul>
</section>
</section>
<section id="summary-of-key-findings" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-key-findings">Summary of Key Findings</h2>
<ul>
<li><strong>61% of flu shot recipients were insured</strong>, compared to 39% who were not — indicating insurance status plays a role in preventive health behavior.</li>
<li><strong>Preventive care usage</strong>, like routine checkups, was significantly higher among individuals with <strong>greater education and income levels</strong>.</li>
<li>A <strong>logistic regression model</strong> showed that <strong>being insured, older, and more educated</strong> were associated with higher odds of getting a flu shot (p &lt; 0.001).</li>
<li>There were observable differences across <strong>racial groups</strong>, highlighting potential disparities in access to or trust in preventive care.</li>
</ul>
</section>
<section id="implications" class="level2">
<h2 class="anchored" data-anchor-id="implications">Implications</h2>
<p>These results suggest that <strong>health insurance access</strong> remains a key driver of preventive healthcare behavior like flu shot uptake. This supports policy efforts aimed at expanding coverage, especially for underserved populations.</p>
</section>
<section id="recommendations" class="level2">
<h2 class="anchored" data-anchor-id="recommendations">Recommendations</h2>
<ul>
<li>Outreach programs targeting low-income groups.</li>
<li>Policy interventions focused on insurance access and preventive care equity.</li>
</ul>
<hr>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>